"""add item description

Revision ID: fa082e0ec1d3
Revises: 56c1e57ed379
Create Date: 2026-09-22 11:47:28.687627

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa082e0ec1d3"
down_revision: str | Sequence[str] | None = "56c1e57ed379"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("description", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "description")
    # ### end Alembic commands ###
